### ISSUE TITLE
Wireframe and code for sites management.

### ISSUE THREAD

**Issue by caniksea** [caniksea/bookui#16]
* [x] Wireframe
* [x] Code implementation

**Comment by caniksea** [comment]
@KeanuDuncan, I have updated the master for your site UI.

**Comment by KeanuDuncan** [comment]
Users and Roles

Users
Super-admin
Site-admin
Site-moderator
Super-moderator
Subscriber

Roles
Super-admin: Create users with privileges.

Site-admin: Add users, delete users, create moderators.

Site-moderator: Add, Edit and Delete books (book management)

Super-moderator: Delete users

Subscriber: View rights.

**Comment by KeanuDuncan** [comment]
[Site Management.pdf](https://github.com/caniksea/bookui/files/2401476/Site.Management.pdf)

**Comment by caniksea** [comment]
> Users and Roles
> 
> Users
> Super-admin
> Site-admin
> Site-moderator
> Super-moderator
> Subscriber
> 
> Roles
> Super-admin: Create users with privileges.
> 
> Site-admin: Add users, delete users, create moderators.
> 
> Site-moderator: Add, Edit and Delete books (book management)
> 
> Super-moderator: Delete users
> 
> Subscriber: View rights.

@KeanuDuncan , put this in the right issue ticket...there is an issue for determining the roles and users of the book api 👎

**Comment by KeanuDuncan** [comment]
Wireframe and code for sites management.

**Comment by caniksea** [comment]
The code/implementation for site management is undone. Why did you close it?
