### ISSUE TITLE
Book, Chapter, Section, Subsection Wireframes

### ISSUE THREAD

**Issue by caniksea** [caniksea/bookui#2]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] Book Wireframes
* [x] Chapters Wire frames
* [x] Sections Wire frames
* [x] Sub-Sections Wire frames

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by NicoleJestine** [comment]
[Wireframe_Admin_BookManagement.pdf](https://github.com/caniksea/bookui/files/2394473/Wireframe_Admin_BookManagement.pdf)
[Wireframe_BlackBook.pdf](https://github.com/caniksea/bookui/files/2394474/Wireframe_BlackBook.pdf)

Please review wire-frames for administrator- Book Management and front-end The Precious Little Black Book.

**Comment by caniksea** [comment]
@NicoleJestine, wireframes and other designs should be reviewed by Prima, my thoughts (Right? @boniface ). She is yet to accept the invitation to collaborate on this project.

**Comment by caniksea** [comment]
> [Wireframe_Admin_BookManagement.pdf](https://github.com/caniksea/bookui/files/2394473/Wireframe_Admin_BookManagement.pdf)
> [Wireframe_BlackBook.pdf](https://github.com/caniksea/bookui/files/2394474/Wireframe_BlackBook.pdf)
> 
> @caniksea Please review wire-frames for administrator- Book Management and front-end The Precious Little Black Book.

@NicoleJestine, although my review on the "Wireframe_Admin_BookManagement.pdf":
1. There should not be another submenu under the child menus (ie Book, Chapter,...). Thus everything concerning Book (as an example) should happen on the display area when you click on the "Book" menu.

**Comment by glorykas** [comment]
Submitted
