### ISSUE TITLE
Create static pages for chapters 1 through 4 on /plbbook

### ISSUE THREAD

**Issue by caniksea** [caniksea/bookui#96]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] Chapter 1
* [x] Chapter 2
* [x] Chapter 3
* [x] Chapter 4

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by NicoleJestine** [comment]
Done
